### ISSUE TITLE
Combat TODO

### ISSUE THREAD

**Issue by ravencrowe01** [ravencrowe01/professor-monster#4]
- [ ] Add hidden flag to combat event
- [ ] Add children list to combat event
- [ ] Status effect handlers
- [ ] CombatState.ProcessEvent -> DispatchEvent
- [ ] Move ability and item trigger processing into CombatMonster
